---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.rahulkshinde.dev
  resources:
  - configrollbacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.rahulkshinde.dev
  resources:
  - configrollbacks/finalizers
  verbs:
  - update
- apiGroups:
  - config.rahulkshinde.dev
  resources:
  - configrollbacks/status
  verbs:
  - get
  - patch
  - update
