//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigRollback) DeepCopyInto(out *ConfigRollback) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRollback.
func (in *ConfigRollback) DeepCopy() *ConfigRollback {
	if in == nil {
		return nil
	}
	out := new(ConfigRollback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigRollback) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigRollbackList) DeepCopyInto(out *ConfigRollbackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigRollback, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRollbackList.
func (in *ConfigRollbackList) DeepCopy() *ConfigRollbackList {
	if in == nil {
		return nil
	}
	out := new(ConfigRollbackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigRollbackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigRollbackSpec) DeepCopyInto(out *ConfigRollbackSpec) {
	*out = *in
	out.TargetService = in.TargetService
	in.HealthChecks.DeepCopyInto(&out.HealthChecks)
	in.RollbackConfig.DeepCopyInto(&out.RollbackConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRollbackSpec.
func (in *ConfigRollbackSpec) DeepCopy() *ConfigRollbackSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigRollbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigRollbackStatus) DeepCopyInto(out *ConfigRollbackStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastHealthCheckTime != nil {
		in, out := &in.LastHealthCheckTime, &out.LastHealthCheckTime
		*out = (*in).DeepCopy()
	}
	if in.LastRollbackTime != nil {
		in, out := &in.LastRollbackTime, &out.LastRollbackTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRollbackStatus.
func (in *ConfigRollbackStatus) DeepCopy() *ConfigRollbackStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigRollbackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsRollbackConfig) DeepCopyInto(out *GitOpsRollbackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsRollbackConfig.
func (in *GitOpsRollbackConfig) DeepCopy() *GitOpsRollbackConfig {
	if in == nil {
		return nil
	}
	out := new(GitOpsRollbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHealthCheck) DeepCopyInto(out *HTTPHealthCheck) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHealthCheck.
func (in *HTTPHealthCheck) DeepCopy() *HTTPHealthCheck {
	if in == nil {
		return nil
	}
	out := new(HTTPHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
	if in.HTTPHealthCheck != nil {
		in, out := &in.HTTPHealthCheck, &out.HTTPHealthCheck
		*out = new(HTTPHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.PrometheusHealthCheck != nil {
		in, out := &in.PrometheusHealthCheck, &out.PrometheusHealthCheck
		*out = new(PrometheusHealthCheck)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaRollbackConfig) DeepCopyInto(out *LambdaRollbackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaRollbackConfig.
func (in *LambdaRollbackConfig) DeepCopy() *LambdaRollbackConfig {
	if in == nil {
		return nil
	}
	out := new(LambdaRollbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusHealthCheck) DeepCopyInto(out *PrometheusHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusHealthCheck.
func (in *PrometheusHealthCheck) DeepCopy() *PrometheusHealthCheck {
	if in == nil {
		return nil
	}
	out := new(PrometheusHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackConfiguration) DeepCopyInto(out *RollbackConfiguration) {
	*out = *in
	if in.WebhookConfig != nil {
		in, out := &in.WebhookConfig, &out.WebhookConfig
		*out = new(WebhookRollbackConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaConfig != nil {
		in, out := &in.LambdaConfig, &out.LambdaConfig
		*out = new(LambdaRollbackConfig)
		**out = **in
	}
	if in.GitOpsConfig != nil {
		in, out := &in.GitOpsConfig, &out.GitOpsConfig
		*out = new(GitOpsRollbackConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackConfiguration.
func (in *RollbackConfiguration) DeepCopy() *RollbackConfiguration {
	if in == nil {
		return nil
	}
	out := new(RollbackConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTarget) DeepCopyInto(out *ServiceTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTarget.
func (in *ServiceTarget) DeepCopy() *ServiceTarget {
	if in == nil {
		return nil
	}
	out := new(ServiceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRollbackConfig) DeepCopyInto(out *WebhookRollbackConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRollbackConfig.
func (in *WebhookRollbackConfig) DeepCopy() *WebhookRollbackConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookRollbackConfig)
	in.DeepCopyInto(out)
	return out
}
